files:
  ignore:
    - 'sass/vendor/**/*.*' 
    - 'css/jazzy.scss' 
    - 'css/syntax.css'
    - 'css/highlight.scss' 
    - 'node_modules/**'
    - 'vendor/bundle/ruby/**'
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem