# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "2.70.1"

default_platform :android

platform :android do

    desc "Beta release app. Deploy a new version to the Google Play Store - Beta channel"
    lane :test do |options|
         Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -c -v 4 ../app/build/outputs/apk/app-release-unsigned.apk", log: true)
         Fastlane::Actions.sh("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../ci/release.keystore ../app/build/outputs/apk/app-release-unsigned.apk 'mdmagent' -keypass " + options[:keypass] + " -storepass " + options[:storepass] + " -tsa http://timestamp.comodoca.com/rfc316 -signedjar ../app/build/outputs/apk/app-release.apk", log: true)
    end
    lane :beta do |options|
         Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -c -v 4 ../app/build/outputs/apk/app-release-unsigned.apk", log: true)
         Fastlane::Actions.sh("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../ci/release.keystore ../app/build/outputs/apk/app-release-unsigned.apk 'mdmagent' -keypass " + options[:keypass] + " -storepass " + options[:storepass] + " -tsa http://timestamp.comodoca.com/rfc316 -signedjar ../app/build/outputs/apk/app-release.apk", log: true)

        supply(
            track: 'beta',
            apk: "../app/build/outputs/apk/app-release.apk"
        )
    end
    lane :playstore do |options|
         Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -c -v 4 ../app/build/outputs/apk/app-release-unsigned.apk", log: true)
         Fastlane::Actions.sh("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../ci/release.keystore ../app/build/outputs/apk/app-release-unsigned.apk 'mdmagent' -keypass " + options[:keypass] + " -storepass " + options[:storepass] + " -tsa http://timestamp.comodoca.com/rfc316 -signedjar ../app/build/outputs/apk/app-release.apk", log: true)


        supply(
            track: 'production',
            apk: "../app/build/outputs/apk/app-release.apk"
        )
    end
end

after_all do |lane|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        repo: ENV["GIT_REPO"],
        branch: ENV["GIT_BRANCH"],
        message: "Fastlane is OK"
    )
end

error do |lane, exception|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        repo: ENV["GIT_REPO"],
        branch: ENV["GIT_BRANCH"],
        message: "`ERROR` Fastlane FAIL"
    )
end

# how to used it fastlane android beta storepass:'#KEYSTORE_PASSWORD' keypass:'#ALIAS_PASSWORD'