# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "2.70.1"

default_platform :android

platform :android do

    desc "Deploy workflow"
    lane :certification do |options|
        Fastlane::Actions.sh("pwd", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -v -p 4 $(ls -dt ../app/build/outputs/apk/fcm/release/*.apk | head -1) ../app/build/outputs/apk/fcm/release/app-release-unsigned-aligned.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner sign --ks ../ci/release.keystore --ks-key-alias mdmagent --ks-pass pass:"+ options[:storepass] +" --key-pass pass:"+ options[:keypass] +"  --out ../app/build/outputs/apk/fcm/release/appCertified.apk ../app/build/outputs/apk/fcm/release/app-release-unsigned-aligned.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner verify ../app/build/outputs/apk/fcm/release/appCertified.apk", log: true)
    end
    lane :alpha do |options|
        supply(
            track: 'alpha',
            apk: "app/build/outputs/apk/fcm/release/appCertified.apk",
            release_status:'draft',
            skip_upload_aab: true
        )
    end
    lane :beta do |options|
        supply(
            track: 'beta',
            apk: "app/build/outputs/apk/fcm/release/appCertified.apk",
            skip_upload_aab: true
        )
    end
    lane :playstore do |options|
        supply(
            track: 'production',
            apk: "app/build/outputs/apk/fcm/release/appCertified.apk",
            skip_upload_aab: true
        )
    end
end

#after_all do |lane|
#UI.error "Something unexpected happened in my_new_action. Attempting to continue."
#end

#error do |lane, exception|
#UI.error "Something unexpected happened in my_new_action. Attempting to continue."
#end

# how to used it fastlane android beta storepass:'#KEYSTORE_PASSWORD' keypass:'#ALIAS_PASSWORD'