# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "2.70.1"

default_platform :android

platform :android do

    desc "Beta release app. Deploy a new version to the Google Play Store - Beta channel"
    lane :cert do |options|
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -v -p 4 ../app/build/outputs/apk/app-release-unsigned.apk ../app/build/outputs/apk/app-release-unsigned-aligned.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner sign --ks ../ci/release.keystore --ks-key-alias mdmagent --ks-pass pass:"+ options[:storepass] +" --key-pass pass:"+ options[:keypass] +"  --out ../app/build/outputs/apk/app-ready.apk ../app/build/outputs/apk/app-release-unsigned-aligned.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner verify ../app/build/outputs/apk/app-ready.apk", log: true)
    end
    lane :beta do |options|
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -c -v 4 ../app/build/outputs/apk/app-release.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner sign --ks ../ci/release.keystore --ks-key-alias mdmagent --ks-pass pass:"+ options[:storepass] +" --key-pass pass:"+ options[:keypass] +"  --out ../app/build/outputs/apk/app-ready.apk ../app/build/outputs/apk/app-release-unsigned-aligned.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner verify ../app/build/outputs/apk/app-ready.apk", log: true)

        supply(
            track: 'beta',
            apk: "../app/build/outputs/apk/app-ready.apk"
        )
    end
    lane :playstore do |options|
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/zipalign -c -v 4 ../app/build/outputs/apk/app-release.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner sign --ks ../ci/release.keystore --ks-key-alias mdmagent --ks-pass pass:"+ options[:storepass] +" --key-pass pass:"+ options[:keypass] +"  --out ../app/build/outputs/apk/app-ready.apk ../app/build/outputs/apk/app-release-unsigned-aligned.apk", log: true)
        Fastlane::Actions.sh("$ANDROID_HOME/build-tools/$BUILD_TOOL/apksigner verify ../app/build/outputs/apk/app-ready.apk", log: true)

        supply(
            track: 'production',
            apk: "../app/build/outputs/apk/app-ready.apk"
        )
    end
end

after_all do |lane|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        repo: ENV["GIT_REPO"],
        branch: ENV["GIT_BRANCH"],
        message: "Fastlane is OK"
    )
end

error do |lane, exception|
    telegram(
        url_horn: ENV["TELEGRAM_WEBHOOKS"],
        repo: ENV["GIT_REPO"],
        branch: ENV["GIT_BRANCH"],
        message: "`ERROR` Fastlane FAIL"
    )
end

# how to used it fastlane android beta storepass:'#KEYSTORE_PASSWORD' keypass:'#ALIAS_PASSWORD'